# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eb859d7e1cc65de5cdfaa768082131e1f02d049377f392ca117bc207402c963849643e3cb7965bd3c9a7ba5ab26b91b6b7cd367021b5c3131572d1fefc58099

test:
  secret_key_base: 2d408c6ddb65f285692ab81a9b505bb2a73f6cdffb91a181e8f22bafd0dc231f4e2144b890ae43fad912d313e875f17d50e9e74d17df45e3236dcb67126a7f72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
